### ISSUE TITLE
Vanity address on Smart Wallet

### ISSUE THREAD

**Issue by mralbertchen** [GokiProtocol/goki#284]
Seems like we can iterate the base keypair to get the vanity address we want?

I have written a small rust cli program here https://github.com/mralbertchen/goki-grinder to help me do that. Can you confirm that I have the right idea?

**Comment by sungoki** [comment]
You are correct!

**Comment by sungoki** [comment]
Also there is another way to "grind" vanity addresses, which is to iterate the derived addresses of any existing smart wallet
